version: 0.0
os: linux
files:
  - source: target/test-app.jar
    destination: /opt/spring-app/
hooks:
  ApplicationStop:
    - location: scripts/stop_application.sh
      runas: ec2-user
  ApplicationStart:
    - location: scripts/start_application.sh
      runas: ec2-user